# EXERCISE 1
def histo( sample ) :
    myhisto = np.zeros(int(max(sample))+1)
    # Your code goes here
    for s in sample:
        myhisto[int(s)] += 1
    return myhisto
# This command loads some data from a file that will be analysed using the function that you 
# write above.  You should not need to modify this command.
data = np.loadtxt("https://raw.githubusercontent.com/autofeedback-exercises/exercises/main/Hypothesis/Homogeniety/one_column.dat")
# This is code that I have written to plot the histogram that will be generated by your function.
# You do not need to modify any of the code.
plt.bar( np.linspace( 0, 7, 8 ), histo( data ), width=0.2)
plt.xlabel("random variable value")
plt.ylabel("counts")
plt.show()

# EXERCISE 2
def contingency_table( all_samples ) : 
    # This command creates a matrix with all_samples.shape[1] rows and 
    table = np.zeros( [all_samples.shape[1],int(np.max(all_samples))+1] )
    # Your code goes here
    for i in range(all_samples.shape[1]):
        table[i,:] = histo( all_samples[:,i] )
    return table
# This command loads some data from a file that will be analysed using the function that you 
# write above.  You should not need to modify this command.
data = np.loadtxt("https://raw.githubusercontent.com/autofeedback-exercises/exercises/main/Hypothesis/Homogeniety/three_column.dat")
# This is code that I have written to plot the three histograms that will be generated by your function.
# You do not need to modify any of the code.
xvals, outtable = np.linspace( 0, 7, 8 ), contingency_table( data )
plt.bar( xvals-0.2, outtable[0,:], width=0.2)
plt.bar( xvals, outtable[1,:], width=0.2)
plt.bar( xvals+0.2, outtable[2,:], width=0.2)
plt.xlabel("random variable value")
plt.ylabel("counts")
plt.show()

# EXERCISE 3
def expectation( table ) : 
    # Your code goes here
    colsums = np.sum( table, axis=1 )
    rowsums = np.sum( table, axis=0 ) 
    outprod = np.outer( colsums, rowsums ) / np.sum(table)
    return outprod
# This command loads some data from a file that will be analysed using the function that you 
# write above.  You should not need to modify this command.
data = np.loadtxt("https://raw.githubusercontent.com/autofeedback-exercises/exercises/main/Hypothesis/Homogeniety/three_column.dat")
# We now use the function that you wrote in the last exercise to compute the contingency table
outtable = contingency_table( data )
# Now we can compute the E_{ij} values from the contingency table
expect = expectation( outtable )
# This is code that I have written to plot the three histograms and the values of E_{ij}
xvals = np.linspace( 0, 7, 8 )
plt.bar( xvals-0.4, outtable[0,:], width=0.2)
plt.bar( xvals-0.2, outtable[1,:], width=0.2)
plt.bar( xvals+0.2, outtable[2,:], width=0.2)
plt.bar( xvals, expect[0,:], width=0.2 )
plt.xlabel("random variable value")
plt.ylabel("counts")
plt.show()

# EXERCISE 4
def teststat( sample ) : 
    table = contingency_table( sample )
    expect = expectation( table )
    # Your code to compute the test statistic goes here
    test_mat = np.divide( (table - expect)**2,  expect, out=np.zeros_like(expect), where=expect!=0 )
    return np.sum(test_mat)
# This command loads some data from a file that will be analysed using the function that you 
# write above.  You should not need to modify this command.
data = np.loadtxt("https://raw.githubusercontent.com/autofeedback-exercises/exercises/main/Hypothesis/Homogeniety/three_column.dat")
print("The test statistic for the data in in the input file is", teststat( data ) )

# EXERCISE 5
def pvalue( sample ) : 
    stat = teststat( sample)
    # Your code to compute the p-value goes here
    ncategories = np.max(sample)+1
    return 1-scipy.stats.chi2.cdf(stat,(ncategories-1)*(sample.shape[1]-1))
# This command loads some data from a file that will be analysed using the function that you 
# write above.  You should not need to modify this command.
data = np.loadtxt("https://raw.githubusercontent.com/autofeedback-exercises/exercises/main/Hypothesis/Homogeniety/three_column.dat")
print("The p-value for the data in in the input file is", pvalue( data ) )
